### ISSUE TITLE
Is INTRO designed to allow for non-textual types of intertextuality?

### ISSUE THREAD

**Issue by alhuber1502** [BOberreither/INTRO#1]
That is to say, how would I model e.g. a pictorial or musical intertext?  This would be a common requirement in comparative literary studies.  I assume this would primarily affect the scope of INT1 and its properties, but would also mean to broaden INT11.  I'd be curious to learn what approach to take for this task?  Thanks!

As E73 Information Object is not restricted to textual entities, INT1 maybe should be conceived more broadly as referring to any section of such an object.  One option would be to re-model references to texts in terms of the [Web Annotation Vocabulary](https://www.w3.org/TR/annotation-vocab/) as oa:Annotation, which would allow for providing bodies and targets media-independently, i.e. from a text, a painting, a piece of music, etc. along the [Media Fragments](https://www.w3.org/TR/media-frags/) specification to point to digital representations of those (a TEI file, a PDF, a JPEG, MP3, MOV, ...).  Thoughts?

**Comment by BOberreither** [comment]
> That is to say, how would I model e.g. a pictorial or musical intertext? This would be a common requirement in comparative literary studies.

Hi! Sorry for the delay. If this is still an issue for you: In the new version (202408), INTRO was expanded to include interpictorial and image-text relations. In this regard, it's an intermedial ontology now. While other media like music were not taken into account and would maybe need more work with regard to feature classes, the central class INT1 Passage now has a scope that can easily include musical passages, with the musical work itself being modeled as a E73 or maybe a F1, F2.
